import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';

/// Catalog of game sound effects.
enum SoundFx {
  cardTap,
  cardMove,
  correct,
  wrong,
  shuffle,
  victory,
  coins,
  button,
}

/// Central sound manager.
///
/// Plays short synthesized WAV effects from `assets/sfx/` (generated by
/// `tool/generate_sounds.dart`) through a small round-robin pool of players so
/// rapid taps can overlap. Players are created lazily on first [play] so the
/// audio engine is never spun up in headless/test contexts. Any failure is
/// swallowed — audio must never break gameplay.
class SoundService {
  SoundService._();
  static final SoundService instance = SoundService._();

  bool soundEnabled = true;
  bool hapticsEnabled = true;

  static const int _poolSize = 4;
  final List<AudioPlayer> _pool = [];
  int _next = 0;
  bool _initialized = false;

  /// Asset path (relative to `assets/`) for each effect.
  static String assetFor(SoundFx fx) {
    switch (fx) {
      case SoundFx.cardTap:
        return 'sfx/card_tap.wav';
      case SoundFx.cardMove:
        return 'sfx/card_move.wav';
      case SoundFx.correct:
        return 'sfx/correct.wav';
      case SoundFx.wrong:
        return 'sfx/wrong.wav';
      case SoundFx.shuffle:
        return 'sfx/shuffle.wav';
      case SoundFx.victory:
        return 'sfx/victory.wav';
      case SoundFx.coins:
        return 'sfx/coins.wav';
      case SoundFx.button:
        return 'sfx/button.wav';
    }
  }

  void _ensureInit() {
    if (_initialized) return;
    _initialized = true;
    for (var i = 0; i < _poolSize; i++) {
      final player = AudioPlayer()..setReleaseMode(ReleaseMode.stop);
      // Low-latency mode is ideal for short SFX (no-op on platforms that lack it).
      player.setPlayerMode(PlayerMode.lowLatency);
      _pool.add(player);
    }
  }

  /// Plays an effect. Safe to call freely; no-ops when sound is disabled and
  /// never throws.
  Future<void> play(SoundFx fx) async {
    if (!soundEnabled) return;
    try {
      _ensureInit();
      final player = _pool[_next];
      _next = (_next + 1) % _pool.length;
      await player.stop();
      await player.play(AssetSource(assetFor(fx)));
    } catch (e) {
      if (kDebugMode) {
        // ignore: avoid_print
        print('SoundService.play(${fx.name}) failed: $e');
      }
    }
  }

  /// Releases the audio players (e.g. on app shutdown).
  Future<void> dispose() async {
    for (final p in _pool) {
      await p.dispose();
    }
    _pool.clear();
    _initialized = false;
  }
}
